[2016-02-09 12:50:49] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /dashboard/"" at F:\work\www\symf.local\symfony_demo\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php line 159 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /dashboard/\" at F:\\work\\www\\symf.local\\symfony_demo\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:159, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at F:\\work\\www\\symf.local\\symfony_demo\\app\\cache\\prod\\appProdUrlMatcher.php:159)"} []
[2016-02-09 12:53:16] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /lucky/number"" at F:\work\www\symf.local\symfony_demo\app\cache\prod\classes.php line 2500 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /lucky/number\" at F:\\work\\www\\symf.local\\symfony_demo\\app\\cache\\prod\\classes.php:2500, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at F:\\work\\www\\symf.local\\symfony_demo\\app\\cache\\prod\\appProdUrlMatcher.php:159)"} []
[2016-02-09 12:57:35] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /ru/api/lucky/number"" at F:\work\www\symf.local\symfony_demo\app\cache\prod\classes.php line 2500 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /ru/api/lucky/number\" at F:\\work\\www\\symf.local\\symfony_demo\\app\\cache\\prod\\classes.php:2500, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at F:\\work\\www\\symf.local\\symfony_demo\\app\\cache\\prod\\appProdUrlMatcher.php:159)"} []
[2016-02-09 12:57:51] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /ru/api/lucky/number"" at F:\work\www\symf.local\symfony_demo\app\cache\prod\classes.php line 2500 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /ru/api/lucky/number\" at F:\\work\\www\\symf.local\\symfony_demo\\app\\cache\\prod\\classes.php:2500, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at F:\\work\\www\\symf.local\\symfony_demo\\app\\cache\\prod\\appProdUrlMatcher.php:159)"} []
[2016-02-09 12:57:56] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /api/lucky/number"" at F:\work\www\symf.local\symfony_demo\app\cache\prod\classes.php line 2500 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /api/lucky/number\" at F:\\work\\www\\symf.local\\symfony_demo\\app\\cache\\prod\\classes.php:2500, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at F:\\work\\www\\symf.local\\symfony_demo\\app\\cache\\prod\\appProdUrlMatcher.php:159)"} []
[2016-02-09 12:58:56] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /lucky/number"" at F:\work\www\symf.local\symfony_demo\app\cache\prod\classes.php line 2500 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /lucky/number\" at F:\\work\\www\\symf.local\\symfony_demo\\app\\cache\\prod\\classes.php:2500, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at F:\\work\\www\\symf.local\\symfony_demo\\app\\cache\\prod\\appProdUrlMatcher.php:159)"} []
[2016-02-09 12:59:08] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /ru/lucky/api/number"" at F:\work\www\symf.local\symfony_demo\app\cache\prod\classes.php line 2500 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /ru/lucky/api/number\" at F:\\work\\www\\symf.local\\symfony_demo\\app\\cache\\prod\\classes.php:2500, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at F:\\work\\www\\symf.local\\symfony_demo\\app\\cache\\prod\\appProdUrlMatcher.php:159)"} []
[2016-02-09 12:59:33] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /ru/api/lucky/number"" at F:\work\www\symf.local\symfony_demo\app\cache\prod\classes.php line 2500 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /ru/api/lucky/number\" at F:\\work\\www\\symf.local\\symfony_demo\\app\\cache\\prod\\classes.php:2500, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at F:\\work\\www\\symf.local\\symfony_demo\\app\\cache\\prod\\appProdUrlMatcher.php:159)"} []
[2016-02-09 13:00:56] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /ru/api/lucky/number"" at F:\work\www\symf.local\symfony_demo\app\cache\prod\classes.php line 2500 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /ru/api/lucky/number\" at F:\\work\\www\\symf.local\\symfony_demo\\app\\cache\\prod\\classes.php:2500, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at F:\\work\\www\\symf.local\\symfony_demo\\app\\cache\\prod\\appProdUrlMatcher.php:159)"} []
[2016-02-09 13:01:04] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /ru/lucky/api/number"" at F:\work\www\symf.local\symfony_demo\app\cache\prod\classes.php line 2500 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /ru/lucky/api/number\" at F:\\work\\www\\symf.local\\symfony_demo\\app\\cache\\prod\\classes.php:2500, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at F:\\work\\www\\symf.local\\symfony_demo\\app\\cache\\prod\\appProdUrlMatcher.php:159)"} []
[2016-02-09 13:02:01] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /ru/lucky/api/number"" at F:\work\www\symf.local\symfony_demo\app\cache\prod\classes.php line 2500 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /ru/lucky/api/number\" at F:\\work\\www\\symf.local\\symfony_demo\\app\\cache\\prod\\classes.php:2500, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at F:\\work\\www\\symf.local\\symfony_demo\\app\\cache\\prod\\appProdUrlMatcher.php:159)"} []
[2016-02-09 13:02:14] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /ru/api/lucky/number"" at F:\work\www\symf.local\symfony_demo\app\cache\prod\classes.php line 2500 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /ru/api/lucky/number\" at F:\\work\\www\\symf.local\\symfony_demo\\app\\cache\\prod\\classes.php:2500, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at F:\\work\\www\\symf.local\\symfony_demo\\app\\cache\\prod\\appProdUrlMatcher.php:159)"} []
[2016-02-09 13:02:29] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /ru/lucky/apinumber"" at F:\work\www\symf.local\symfony_demo\app\cache\prod\classes.php line 2500 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /ru/lucky/apinumber\" at F:\\work\\www\\symf.local\\symfony_demo\\app\\cache\\prod\\classes.php:2500, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at F:\\work\\www\\symf.local\\symfony_demo\\app\\cache\\prod\\appProdUrlMatcher.php:159)"} []
[2016-02-09 13:02:49] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /ru/lucky/apinumber"" at F:\work\www\symf.local\symfony_demo\app\cache\prod\classes.php line 2500 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /ru/lucky/apinumber\" at F:\\work\\www\\symf.local\\symfony_demo\\app\\cache\\prod\\classes.php:2500, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at F:\\work\\www\\symf.local\\symfony_demo\\app\\cache\\prod\\appProdUrlMatcher.php:159)"} []
[2016-02-09 13:02:54] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /ru/lucky/api/number"" at F:\work\www\symf.local\symfony_demo\app\cache\prod\classes.php line 2500 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /ru/lucky/api/number\" at F:\\work\\www\\symf.local\\symfony_demo\\app\\cache\\prod\\classes.php:2500, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at F:\\work\\www\\symf.local\\symfony_demo\\app\\cache\\prod\\appProdUrlMatcher.php:159)"} []
[2016-02-09 13:03:15] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /ru/api/number"" at F:\work\www\symf.local\symfony_demo\app\cache\prod\classes.php line 2500 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /ru/api/number\" at F:\\work\\www\\symf.local\\symfony_demo\\app\\cache\\prod\\classes.php:2500, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at F:\\work\\www\\symf.local\\symfony_demo\\app\\cache\\prod\\appProdUrlMatcher.php:159)"} []
[2016-02-09 13:03:25] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /ru/api/lucky/number"" at F:\work\www\symf.local\symfony_demo\app\cache\prod\classes.php line 2500 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /ru/api/lucky/number\" at F:\\work\\www\\symf.local\\symfony_demo\\app\\cache\\prod\\classes.php:2500, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at F:\\work\\www\\symf.local\\symfony_demo\\app\\cache\\prod\\appProdUrlMatcher.php:159)"} []
[2016-02-09 13:03:34] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /ru/api/lucky/number"" at F:\work\www\symf.local\symfony_demo\app\cache\prod\classes.php line 2500 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /ru/api/lucky/number\" at F:\\work\\www\\symf.local\\symfony_demo\\app\\cache\\prod\\classes.php:2500, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at F:\\work\\www\\symf.local\\symfony_demo\\app\\cache\\prod\\appProdUrlMatcher.php:159)"} []
[2016-02-09 13:03:51] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /ru/api/lucky/number"" at F:\work\www\symf.local\symfony_demo\app\cache\prod\classes.php line 2500 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /ru/api/lucky/number\" at F:\\work\\www\\symf.local\\symfony_demo\\app\\cache\\prod\\classes.php:2500, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at F:\\work\\www\\symf.local\\symfony_demo\\app\\cache\\prod\\appProdUrlMatcher.php:159)"} []
[2016-02-09 13:03:52] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /ru/api/lucky/number"" at F:\work\www\symf.local\symfony_demo\app\cache\prod\classes.php line 2500 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /ru/api/lucky/number\" at F:\\work\\www\\symf.local\\symfony_demo\\app\\cache\\prod\\classes.php:2500, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at F:\\work\\www\\symf.local\\symfony_demo\\app\\cache\\prod\\appProdUrlMatcher.php:159)"} []
[2016-02-09 13:05:09] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /api/lucky/number/"" at F:\work\www\symf.local\symfony_demo\app\cache\prod\classes.php line 2500 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /api/lucky/number/\" at F:\\work\\www\\symf.local\\symfony_demo\\app\\cache\\prod\\classes.php:2500, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at F:\\work\\www\\symf.local\\symfony_demo\\app\\cache\\prod\\appProdUrlMatcher.php:159)"} []
[2016-02-09 13:05:17] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /ru/api/lucky/number/"" at F:\work\www\symf.local\symfony_demo\app\cache\prod\classes.php line 2500 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /ru/api/lucky/number/\" at F:\\work\\www\\symf.local\\symfony_demo\\app\\cache\\prod\\classes.php:2500, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at F:\\work\\www\\symf.local\\symfony_demo\\app\\cache\\prod\\appProdUrlMatcher.php:159)"} []
[2016-02-09 13:13:57] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /ru/api/lucky/number/"" at F:\work\www\symf.local\symfony_demo\app\cache\prod\classes.php line 2500 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /ru/api/lucky/number/\" at F:\\work\\www\\symf.local\\symfony_demo\\app\\cache\\prod\\classes.php:2500, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at F:\\work\\www\\symf.local\\symfony_demo\\app\\cache\\prod\\appProdUrlMatcher.php:159)"} []
[2016-02-09 13:14:01] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /ru/lucky/number/"" at F:\work\www\symf.local\symfony_demo\app\cache\prod\classes.php line 2500 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /ru/lucky/number/\" at F:\\work\\www\\symf.local\\symfony_demo\\app\\cache\\prod\\classes.php:2500, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at F:\\work\\www\\symf.local\\symfony_demo\\app\\cache\\prod\\appProdUrlMatcher.php:159)"} []
[2016-02-09 13:14:09] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /ru/lucky/number/"" at F:\work\www\symf.local\symfony_demo\app\cache\prod\classes.php line 2500 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /ru/lucky/number/\" at F:\\work\\www\\symf.local\\symfony_demo\\app\\cache\\prod\\classes.php:2500, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at F:\\work\\www\\symf.local\\symfony_demo\\app\\cache\\prod\\appProdUrlMatcher.php:159)"} []
[2016-02-09 13:14:20] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /ru/api/lucky/number"" at F:\work\www\symf.local\symfony_demo\app\cache\prod\classes.php line 2500 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /ru/api/lucky/number\" at F:\\work\\www\\symf.local\\symfony_demo\\app\\cache\\prod\\classes.php:2500, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at F:\\work\\www\\symf.local\\symfony_demo\\app\\cache\\prod\\appProdUrlMatcher.php:159)"} []
[2016-02-09 13:14:30] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /ru/lucky/api/number"" at F:\work\www\symf.local\symfony_demo\app\cache\prod\classes.php line 2500 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /ru/lucky/api/number\" at F:\\work\\www\\symf.local\\symfony_demo\\app\\cache\\prod\\classes.php:2500, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at F:\\work\\www\\symf.local\\symfony_demo\\app\\cache\\prod\\appProdUrlMatcher.php:159)"} []
[2016-02-09 13:14:30] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /ru/lucky/api/number"" at F:\work\www\symf.local\symfony_demo\app\cache\prod\classes.php line 2500 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /ru/lucky/api/number\" at F:\\work\\www\\symf.local\\symfony_demo\\app\\cache\\prod\\classes.php:2500, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at F:\\work\\www\\symf.local\\symfony_demo\\app\\cache\\prod\\appProdUrlMatcher.php:159)"} []
[2016-02-09 13:22:59] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /ru/lucky/number/7"" at F:\work\www\symf.local\symfony_demo\app\cache\prod\classes.php line 2500 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /ru/lucky/number/7\" at F:\\work\\www\\symf.local\\symfony_demo\\app\\cache\\prod\\classes.php:2500, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at F:\\work\\www\\symf.local\\symfony_demo\\app\\cache\\prod\\appProdUrlMatcher.php:159)"} []
[2016-02-09 13:23:02] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /ru/lucky/number/7"" at F:\work\www\symf.local\symfony_demo\app\cache\prod\classes.php line 2500 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /ru/lucky/number/7\" at F:\\work\\www\\symf.local\\symfony_demo\\app\\cache\\prod\\classes.php:2500, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at F:\\work\\www\\symf.local\\symfony_demo\\app\\cache\\prod\\appProdUrlMatcher.php:159)"} []
[2016-02-09 13:23:09] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /lucky/number/7"" at F:\work\www\symf.local\symfony_demo\app\cache\prod\classes.php line 2500 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /lucky/number/7\" at F:\\work\\www\\symf.local\\symfony_demo\\app\\cache\\prod\\classes.php:2500, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at F:\\work\\www\\symf.local\\symfony_demo\\app\\cache\\prod\\appProdUrlMatcher.php:159)"} []
[2016-02-09 13:23:57] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /lucky/number/7"" at F:\work\www\symf.local\symfony_demo\app\cache\prod\classes.php line 2500 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /lucky/number/7\" at F:\\work\\www\\symf.local\\symfony_demo\\app\\cache\\prod\\classes.php:2500, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at F:\\work\\www\\symf.local\\symfony_demo\\app\\cache\\prod\\appProdUrlMatcher.php:159)"} []
[2016-02-09 13:24:03] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /ru/lucky/number/7"" at F:\work\www\symf.local\symfony_demo\app\cache\prod\classes.php line 2500 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /ru/lucky/number/7\" at F:\\work\\www\\symf.local\\symfony_demo\\app\\cache\\prod\\classes.php:2500, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at F:\\work\\www\\symf.local\\symfony_demo\\app\\cache\\prod\\appProdUrlMatcher.php:159)"} []
[2016-02-09 13:24:04] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /ru/lucky/number/7"" at F:\work\www\symf.local\symfony_demo\app\cache\prod\classes.php line 2500 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /ru/lucky/number/7\" at F:\\work\\www\\symf.local\\symfony_demo\\app\\cache\\prod\\classes.php:2500, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at F:\\work\\www\\symf.local\\symfony_demo\\app\\cache\\prod\\appProdUrlMatcher.php:159)"} []
[2016-02-09 13:25:09] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /ru/lucky/number/10"" at F:\work\www\symf.local\symfony_demo\app\cache\prod\classes.php line 2500 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /ru/lucky/number/10\" at F:\\work\\www\\symf.local\\symfony_demo\\app\\cache\\prod\\classes.php:2500, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at F:\\work\\www\\symf.local\\symfony_demo\\app\\cache\\prod\\appProdUrlMatcher.php:159)"} []
[2016-02-09 13:31:41] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /ru/lucky/number/10"" at F:\work\www\symf.local\symfony_demo\app\cache\prod\classes.php line 2500 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /ru/lucky/number/10\" at F:\\work\\www\\symf.local\\symfony_demo\\app\\cache\\prod\\classes.php:2500, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at F:\\work\\www\\symf.local\\symfony_demo\\app\\cache\\prod\\appProdUrlMatcher.php:159)"} []
[2016-03-03 19:02:47] request.INFO: Matched route "lucky_number". {"route_parameters":{"_controller":"TestBundle\\Controller\\LuckyController::numberAction","count":3,"_locale":"ru","_route":"lucky_number"},"request_uri":"http://symf.local/ru/lucky/number"} []
[2016-03-03 19:03:08] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occured in driver: SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it. " at D:\work\www\symftest\symfony_demo\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 103 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it.\r\n at D:\\work\\www\\symftest\\symfony_demo\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 2002): SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it.\r\n at D:\\work\\www\\symftest\\symfony_demo\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:47, PDOException(code: 2002): SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it.\r\n at D:\\work\\www\\symftest\\symfony_demo\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:43)"} []
[2016-03-03 19:03:35] php.CRITICAL: Fatal Error: Maximum execution time of 60 seconds exceeded {"type":1,"file":"D:\\work\\www\\symftest\\symfony_demo\\vendor\\twig\\twig\\lib\\Twig\\TokenParserBroker.php","line":20,"level":6143,"stack":[{"file":"D:\\work\\www\\symftest\\symfony_demo\\vendor\\composer\\ClassLoader.php","line":412,"include_filename":"D:\\work\\www\\symftest\\symfony_demo\\vendor\\twig\\twig\\lib\\Twig\\TokenParserBroker.php","args":[]},{"function":"Composer\\Autoload\\includeFile","file":"D:\\work\\www\\symftest\\symfony_demo\\vendor\\composer\\ClassLoader.php","line":301,"args":[]},{"function":"loadClass","type":"->","class":"Composer\\Autoload\\ClassLoader","file":"D:\\work\\www\\symftest\\symfony_demo\\app\\cache\\prod\\classes.php","line":0,"args":[]},{"function":"spl_autoload_call","file":"D:\\work\\www\\symftest\\symfony_demo\\app\\cache\\prod\\classes.php","line":4098,"args":[]},{"function":"initExtensions","type":"->","class":"Twig_Environment","file":"D:\\work\\www\\symftest\\symfony_demo\\app\\cache\\prod\\classes.php","line":4056,"args":[]},{"function":"getUnaryOperators","type":"->","class":"Twig_Environment","file":"D:\\work\\www\\symftest\\symfony_demo\\vendor\\twig\\twig\\lib\\Twig\\Lexer.php","line":371,"args":[]},{"function":"getOperatorRegex","type":"->","class":"Twig_Lexer","file":"D:\\work\\www\\symftest\\symfony_demo\\vendor\\twig\\twig\\lib\\Twig\\Lexer.php","line":65,"args":[]},{"function":"__construct","type":"->","class":"Twig_Lexer","file":"D:\\work\\www\\symftest\\symfony_demo\\app\\cache\\prod\\classes.php","line":3720,"args":[]},{"function":"getLexer","type":"->","class":"Twig_Environment","file":"D:\\work\\www\\symftest\\symfony_demo\\app\\cache\\prod\\classes.php","line":3730,"args":[]},{"function":"tokenize","type":"->","class":"Twig_Environment","file":"D:\\work\\www\\symftest\\symfony_demo\\app\\cache\\prod\\classes.php","line":3765,"args":[]},{"function":"compileSource","type":"->","class":"Twig_Environment","file":"D:\\work\\www\\symftest\\symfony_demo\\app\\cache\\prod\\classes.php","line":3647,"args":[]},{"function":"loadTemplate","type":"->","class":"Twig_Environment","file":"D:\\work\\www\\symftest\\symfony_demo\\app\\cache\\prod\\classes.php","line":3625,"args":[]},{"function":"render","type":"->","class":"Twig_Environment","file":"D:\\work\\www\\symftest\\symfony_demo\\vendor\\symfony\\symfony\\src\\Symfony\\Bundle\\TwigBundle\\Controller\\ExceptionController.php","line":74,"args":[]},{"function":"showAction","type":"->","class":"Symfony\\Bundle\\TwigBundle\\Controller\\ExceptionController","file":"D:\\work\\www\\symftest\\symfony_demo\\app\\bootstrap.php.cache","line":3109,"args":[]},{"function":"call_user_func_array:{D:\\work\\www\\symftest\\symfony_demo\\app\\bootstrap.php.cache:3109}","file":"D:\\work\\www\\symftest\\symfony_demo\\app\\bootstrap.php.cache","line":3109,"args":[]},{"function":"handleRaw","type":"->","class":"Symfony\\Component\\HttpKernel\\HttpKernel","file":"D:\\work\\www\\symftest\\symfony_demo\\app\\bootstrap.php.cache","line":3071,"args":[]},{"function":"handle","type":"->","class":"Symfony\\Component\\HttpKernel\\HttpKernel","file":"D:\\work\\www\\symftest\\symfony_demo\\app\\bootstrap.php.cache","line":3222,"args":[]},{"function":"handle","type":"->","class":"Symfony\\Component\\HttpKernel\\DependencyInjection\\ContainerAwareHttpKernel","file":"D:\\work\\www\\symftest\\symfony_demo\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\ExceptionListener.php","line":50,"args":[]},{"function":"onKernelException","type":"->","class":"Symfony\\Component\\HttpKernel\\EventListener\\ExceptionListener","file":"D:\\work\\www\\symftest\\symfony_demo\\app\\cache\\prod\\classes.php","line":2272,"args":[]},{"function":"call_user_func:{D:\\work\\www\\symftest\\symfony_demo\\app\\cache\\prod\\classes.php:2272}","file":"D:\\work\\www\\symftest\\symfony_demo\\app\\cache\\prod\\classes.php","line":2272,"args":[]},{"function":"doDispatch","type":"->","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","file":"D:\\work\\www\\symftest\\symfony_demo\\app\\cache\\prod\\classes.php","line":2201,"args":[]},{"function":"dispatch","type":"->","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","file":"D:\\work\\www\\symftest\\symfony_demo\\app\\bootstrap.php.cache","line":3141,"args":[]},{"function":"handleException","type":"->","class":"Symfony\\Component\\HttpKernel\\HttpKernel","file":"D:\\work\\www\\symftest\\symfony_demo\\app\\bootstrap.php.cache","line":3077,"args":[]},{"function":"handle","type":"->","class":"Symfony\\Component\\HttpKernel\\HttpKernel","file":"D:\\work\\www\\symftest\\symfony_demo\\app\\bootstrap.php.cache","line":3222,"args":[]},{"function":"handle","type":"->","class":"Symfony\\Component\\HttpKernel\\DependencyInjection\\ContainerAwareHttpKernel","file":"D:\\work\\www\\symftest\\symfony_demo\\app\\bootstrap.php.cache","line":2444,"args":[]},{"function":"handle","type":"->","class":"Symfony\\Component\\HttpKernel\\Kernel","file":"D:\\work\\www\\symftest\\symfony_demo\\web\\app.php","line":44,"args":[]},{"function":"{main}","file":"D:\\work\\www\\symftest\\symfony_demo\\web\\app.php","line":0,"args":[]}]} []
[2016-03-03 19:03:36] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Error: Maximum execution time of 60 seconds exceeded" at D:\work\www\symftest\symfony_demo\vendor\twig\twig\lib\Twig\TokenParserBroker.php line 20 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Maximum execution time of 60 seconds exceeded at D:\\work\\www\\symftest\\symfony_demo\\vendor\\twig\\twig\\lib\\Twig\\TokenParserBroker.php:20)"} []
